.github/workflows/run_tests.yml, ci/ci.sh, ci/jest-reporter.js, package.json
We want to manually trigger the tests to run on our infrastructure from GitHub Actions.
- Added CI workflow to launch ECS task that runs the tests
- Updated jest-reporter to send discord message when the test run starts and when it completes
Uses the infra updates already on dev (https://github.com/3box/ceramic-infra/pull/245)
=> Run tests with CI

Dockerfile, ci/jest.config.ci.js, jest.config.js, package.json, src/__tests__/ceramic_state_store.ts
Was getting an error because the config wasn't copied into docker.
Also had typos where the jest services config object needed to be updated.
- Moved jest config from package.json to jest.config.js to easily use it in ci
- Fixed typos
=> Fix jest config

ci/jest-reporter.js
Now displays like this in discord
=> fix: print tests passed if not failed tests

src/__tests__/ceramic_cas.ts, src/__tests__/ceramic_ceramic.ts
I've noticed the tests failed once or twice when the CAS anchor eth txn times out multiple times, but ultimately is successful.
Rough math that shows this actually does make sense:
* Anchor happens every 5 minutes
* Each eth txn has a 3 minute timeout, and we get 3 attempts
5 + (3 * 3) = 14 minutes, rounded up to 15 for good measure
=> chore(tests): Increase anchor timeout to account for txn timeouts and retries

.github/workflows/run_tests.yml, config/env/local_node-internal.json, package-lock.json
We have been using the ceramic-dev-node bucket for the state store when a node gets created by jest but we should use a test bucket instead.
=> fix: use test bucket for state store

src/__tests__/ceramic_ceramic.ts
Just on the off chance that the reason it's failing in local_node env is that that env moves slower.  Seems unlikely to be the cause but I just want to rule out that waiting longer would make it work
=> Increase update timeout to 1 minute

src/__tests__/key_revocation.ts
I'm not positive this will fix *everything* but it is necessary because we wait for anchors and it will allow us to see if any other issues are present.
=> fix: increase jest timeout for key revocation

src/__tests__/key_revocation.ts
So, if `tile.update` works, it just passes control over to the current line of code.
=> fix: Adjust for tile.update returns Promise<void>

src/__tests__/ceramic_cas.ts, src/__tests__/ceramic_ceramic.ts, src/__tests__/key_revocation.ts, src/utils.ts
With the restart loop in place for the cas on dev, the time between anchors is longer than normal as we have to wait for ipfs and ceramic to shutdown and restart between every batch.  This is making integration tests fail.  So for now let's increase the test timeouts, and we can set them back once we are using go-ipfs and remove the restart loop.
=> chore: Temporarily increase integration test timeouts

.github/workflows/build_and_push_ecr.yml, .github/workflows/run_tests.yml
- deploy to and run on qa infra instead of dev
- use dev-qa ceramic network instead of dev-unstable
=> CI for qa env

src/index.ts
We have to clean the state store on teardown, not on setup
because we are using the ceramic node to remove its pins
And the ceramic node will not start if the state store has old data
=> Must clean state store in teardown not setup

src/__tests__/indexing.ts
Received errors such as this: 
```
● indexing › Using existing model › Can filter by DID across nodes -- creating: ceramicClient, loading: ceramic
expect(received).toBeGreaterThanOrEqual(expected)
Expected: >= 1
Received:    0
308 |             .query({ model: TEST_MODEL, last: 100, account: did2.id })
309 |             .then(resultObj => extractDocuments(ceramic2, resultObj))
> 310 |           expect(did2Results.length).toBeGreaterThanOrEqual(1)
|                                      ^
311 |
312 |           const lastDid2Doc = did2Results.at(-1) as ModelInstanceDocument
313 |           expect(lastDid2Doc.id.toString()).toEqual(doc2.id.toString())
at toBeGreaterThanOrEqual (src/__tests__/indexing.ts:310:38)
```
logs show errors: 
```
[2022-11-15T09:41:19.581Z] ERROR: Error [ReadError]: …
```
=> fix: increase wait for commits between cross node indexing queries

src/index.ts
Trying to bandaid the flakiness we're seeing with https://linear.app/3boxlabs/issue/CDB-2096/e2e-test-local-node-private-config-flaky-due-to-node-restarting-mid
=> Sleep before tearing down tests

package-lock.json, package.json, src/__tests__/indexing.ts
fixes two things:
- we cannot control the order we receive pubsub messages. We cannot expect the most recently indexed mid to be the one we created
- sometimes it takes a while to receive mids created by a remote node. We attempted to use a delay but sometimes it is not enough. So i am using a polling strategy
=> fix: wait for mids to be indexed

src/__tests__/ceramic_cas.ts
It's not a safe assumption and it's making the tests flaky.
=> fix: don't assume that writes will be anchored in the same batch

src/utils.ts
The call to initialize s3 needed to be updated to a new parameter order based on the dependency upgrade. 
Running the tests locally produced an error about `null.dev-unstable` after making this change the error was resolved.
Before submitting this PR, please make sure:
Please list relevant documentation (e.g. tech specs, articles, related work etc.) relevant to this change, and note if the documentation has been updated.
=> fix: update s3 call with the new API

src/__tests__/ceramic_state_store.ts
Update test code to use new API of `ceramic.admin.pin.*` instead of `ceramic.pin.*`. 
Locally ran tests
Before submitting this PR, please make sure:
Please list relevant documentation (e.g. tech specs, articles, related work etc.) relevant to this change, and note if the documentation has been updated.
=> fix: use new pin api under admin namespace

package-lock.json, package.json
We needed to name the kubo-rpc-client dependency version explicitly to talk to Kubo 18 successfully.
Ran tests locally
Before submitting this PR, please make sure:
Please list relevant documentation (e.g. tech specs, articles, related work etc.) relevant to this change, and note if the documentation has been updated.
=> fix: add explicit dependency on kubo-rpc-client

ci/ci.sh
The `$()` syntax will execute the output as a command. As it was written the first line of output (i.e. a log message) will be executed as a command.
Ran tests locally
=> fix: remove the extra command execution from ci.sh

.editorconfig, src/__tests__/indexing.ts
By definition `null`s are allowed. I do not know, why the code is that strict here.
=> chore: Allow nulls
